### ISSUE TITLE
play/pause buttons shouldn't hide the last terminal line

### ISSUE THREAD

**Issue by delgod** [asciinema/asciinema-player#130] opened 2020-01-17 07:52 UTC
Thank you @sickill! Amazing project!
I would love to see minor UX improvement -- control panel shouldn't be part of the screencast.
it is often needed to pause screen and look at what the author is typing or what message was returned in the last line of the screen, but in 99% cases, this line is hidden by a control panel with play/pause buttons and timeline.

**Comment by nicolas17** [comment] 2020-07-29 03:11
Duplicate of #115?

**Comment by delgod** [comment] 2020-08-17 09:39
> Duplicate of #115?

yes

**Closed** 2020-08-17 09:39 UTC
