### ISSUE TITLE
\u000e character screws up the web player

### ISSUE THREAD

**Issue by rmoff** [asciinema/asciinema-player#93] opened 2018-07-05 17:10 UTC
I ❤️ asciinema :) Today though I have a problem with the recording when it's uploaded and played on asciinema.org. 

Locally, it renders correctly:
![image](https://user-images.githubusercontent.com/3671582/42337340-67e912ae-807e-11e8-8f94-89300c055470.png)

[On the server](https://asciinema.org/a/nCFSAuPwe9fdXFnt186Rloryx?t=25) it renders like this - note the funny chars from about a quarter of the screen down onwards: 

![image](https://user-images.githubusercontent.com/3671582/42337368-89b412bc-807e-11e8-90f7-5e719d6f1c8a.png)

Anything I can do to fix this? Thanks!

[Source cast file](https://gist.github.com/8e72dd1975cda5d97cce553716c8cc0f)

**Comment by rmoff** [comment] 2018-07-05 17:17
I think it might be `\u000e` here:  https://gist.github.com/rmoff/8e72dd1975cda5d97cce553716c8cc0f#file-tmpkeskvzmm-ascii-cast-L88

**Comment by rmoff** [comment] 2018-07-05 17:18
Confirmed - if I change `\u000e` in the source to `\u000f` it works fine in the web player: https://asciinema.org/a/8IoJQ3ZahMTXhk8Az3OQ5DJGz

**Comment by mathieu-aubin** [comment] 2018-07-05 21:44
I noticed in the [Gist](https://gist.github.com/rmoff/8e72dd1975cda5d97cce553716c8cc0f#file-tmpkeskvzmm-ascii-cast-L88) you are linking that $TERM is set to _'screen'_ instead of a somewhat usual _xterm_ / _xterm-256color_ / _screen-256color_

I am thinking that you are recorsing from inside a screen, is this correct?

I have yet to investigate on this and i must stress i am **_NO VT-MEiSTER_** but i would think it could have something to do with that?

----- After writing all this stuff -----

I have seen this issue #91 which is pretty much exactly the same

**Comment by sickill** [comment] 2021-12-11 18:35
Thanks for investigating 👌 

Since this is a duplicate of #91 I'm going to close this one though.

**Closed by sickill** 2021-12-11 18:35 UTC
Labels: bug, emulation

**Comment by sickill** [comment] 2021-12-11 18:36
This is something to fix in the vt implementation therefore I've moved #91 to https://github.com/asciinema/vt-rs/issues/6
