### ISSUE TITLE
Navbar is hiding content on the bottom

### ISSUE THREAD

**Issue by jtagcat** [asciinema/asciinema-player#115] opened 2019-07-26 17:41 UTC
When there is any text behind the navbar, make the navbar go to the top, instead of sticking to the bottom, or don't let any text go behind it.

(this is the navbar, if you didn't get it)
![image](https://user-images.githubusercontent.com/38327267/61970588-a2bd1280-afcc-11e9-967c-3c937b8cd4a0.png)

**Comment by sickill** [comment] 2022-06-19 19:41
Duplicate of #90.

**Comment by Bouhrich** [comment] 2022-06-19 19:42
Le dim. 19 jui. 2022 à 20:41, Marcin Kulik ***@***.***> a
écrit :

**Closed** 2022-06-19 19:41 UTC
