### ISSUE TITLE
Playback creates characters not in original

### ISSUE THREAD

**Issue by chris-sanders** [asciinema/asciinema-player#186] opened 2022-05-22 15:46 UTC
I'm not positive which part of the project this affects my best guess is the player so I'm filing it here.

I'm using ZSH and my recordings work locally but when using the asciinema2gif or uploading to asciinema.org the playback files show extra characters and echo statements that aren't present using the local `asciinema play` command and aren't displayed in the actual terminal while recording.

[![asciicast](https://asciinema.org/a/1WeepQwzH62H2T8DHlc1J5Dst.svg)](https://asciinema.org/a/1WeepQwzH62H2T8DHlc1J5Dst)

This is a simple example, but during recording and local playback this is what the actual output is.
<img width="257" alt="Screen Shot 2022-05-22 at 10 44 52 AM" src="https://user-images.githubusercontent.com/813115/169703946-d5a4256b-ef6f-4d64-93e5-b10284493209.png">

I'm not sure how to troubleshoot this since it only shows up when rendering a gif or on the website. Local capture and playback work as expected.

**Comment by sickill** [comment] 2022-05-22 17:09
This is how it looks when I play it in my terminal (alacritty, fish):

![image](https://user-images.githubusercontent.com/17589/169707076-601f86bf-de32-42a4-a2a5-4ab5731faa60.png)

I get that extra `echo` too. 

What's your terminal and shell?

**Comment by chris-sanders** [comment] 2022-05-22 18:15
I'm using Terminal for Macos with zsh. I disabled my prompt customization
just to check and that didn't change anything about the echo.

**Comment by sickill** [comment] 2022-05-22 18:43
I made additional test under xterm+bash:

![image](https://user-images.githubusercontent.com/17589/169710694-d8053812-bc95-4fc0-80fa-48908e24121b.png)

I suspect there's something special about your local setup as I can't reproduce this in any way.

**Comment by sickill** [comment] 2022-05-22 18:53
Here's the line in your recording which is responsible for the additional "echo":

```json
[4.734315, "o", "\u001bkecho\u001b\\"]
```

"echo" is follow by escape sequence `\u001bk` which is `\ek`. I'm not aware of such escape code. xterm, alacritty and asciinema-player just ignore this escape sequence and just print what follows it, which is "echo".

**Comment by chris-sanders** [comment] 2022-05-22 19:15
Ok interesting I'll see if there's something in Terminal that might affect this

**Comment by chris-sanders** [comment] 2022-05-22 19:31
Ok I've been playing with it some more, tmux introduces this. I completely forgot to mention tmux. I launch tmux with my shell. Even removing the .tmux.conf file to run completely stock recording a session inside tmux looks fine when played back from inside tmux but adds the extra echo characters if played outside of tmux.

I guess as a workaround I can just drop out of tmux anytime I'm recording, I'm curious if there's anything you know of that I could set on tmux so I don't have to remember to do that when I create a recording.

**Comment by chris-sanders** [comment] 2022-05-22 19:58
Ah found it!
ZSH auto-detects tmux and enables automatic pane renaming, which use the \ek escape. I can disable automatic pane renaming and sure enough it's displayed correctly after that both in and out of a tmux session.

Is there anything I can do with asciinema to ignore this escape sequence so I can continue to use the auto-rename in tmux? If not I should be able to manually name a pane before starting the recording which prevents automatic renames and should also work.

**Comment by sickill** [comment] 2022-05-23 08:35
Great sleuthing! I think we can easily ignore that.

However I'm wondering if it's good idea in general since no terminal emulator I tested is doing that. But I guess they probably don't need to do anything special when you use tmux as tmux is handling and swallowing those seqs before they hit your term.

**Comment by chris-sanders** [comment] 2022-05-23 13:05
Yea the more I think about it, this is an edge case. The fact that the shell has been configured to send commands for the multiplexer is a bit unusual. I didn't try it I guess this would show up on any multiplexer (tmux, screen, etc) if you use hotkeys to resize/search etc? I wonder if there's a more generic 'ignore all escape sequences' that would apply generically to multiplexers? I'm not very familiar if there's a standard for those or if they are all just custom.

**Comment by sickill** [comment] 2023-02-06 14:42
Since we found this to be an edge case, and player's behaviour is consistent with most popular terminal emulators, I'm going to close this for now.

**Closed by sickill** 2023-02-06 14:42 UTC
